server:
  port: 8080
  domain: http://127.0.0.1:8080

spring:
  profiles:
    active: @platform@,@deployment@,@db.type@
  application:
    name: aigc-platform-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 101MB
  mvc:
    async:
      request-timeout: 600000

  datasource:
    url: jdbc:mysql:///aigc_platform?rewriteBatchedStatements=true&useServerPrepStmts=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

remote:
  enable: false
  platform: unix
  model-dir: /model


---
spring:
  config:
    activate:
      on-profile: sqlite
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:aigc_platform.db
    username:
    password: