server:
  port: 8080

spring:
  application:
    name: aigc-platform-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 101MB
  mvc:
    async:
      request-timeout: 600000

remote:
  enable: false
  platform: unix
  model-dir: /model